In [415]:
import pandas as pd
import numpy as np
import seaborn as sns

In [416]:
borrower=pd.read_csv('borrower_table.csv')
loan=pd.read_csv('loan_table.csv')

In [417]:
loan.shape, borrower.shape,loan.columns,borrower.columns

((101100, 5),
 (101100, 12),
 Index(['loan_id', 'loan_purpose', 'date', 'loan_granted', 'loan_repaid'], dtype='object'),
 Index(['loan_id', 'is_first_loan', 'fully_repaid_previous_loans',
        'currently_repaying_other_loans', 'total_credit_card_limit',
        'avg_percentage_credit_card_limit_used_last_year', 'saving_amount',
        'checking_amount', 'is_employed', 'yearly_salary', 'age',
        'dependent_number'],
       dtype='object'))

In [443]:

df=pd.merge(loan,borrower,on=['loan_id'])
df = df[df['loan_granted']==1]

In [444]:
df.columns

Index(['loan_id', 'loan_purpose', 'date', 'loan_granted', 'loan_repaid',
       'is_first_loan', 'fully_repaid_previous_loans',
       'currently_repaying_other_loans', 'total_credit_card_limit',
       'avg_percentage_credit_card_limit_used_last_year', 'saving_amount',
       'checking_amount', 'is_employed', 'yearly_salary', 'age',
       'dependent_number'],
      dtype='object')

In [445]:
df.head()

,loan_id,loan_purpose,date,loan_granted,loan_repaid,is_first_loan,fully_repaid_previous_loans,currently_repaying_other_loans,total_credit_card_limit,avg_percentage_credit_card_limit_used_last_year,saving_amount,checking_amount,is_employed,yearly_salary,age,dependent_number
3,580653,other,2012-06-27,1,1.0,0,1.0,0.0,5400,0.52,3345,2764,1,15800,58,4
4,172419,business,2012-05-21,1,0.0,1,NaN,NaN,2900,0.76,1050,3695,1,34800,31,4
6,780070,business,2012-03-14,1,1.0,0,1.0,0.0,7800,0.30,4206,4368,1,51100,51,2
7,303138,emergency_funds,2012-08-31,1,0.0,0,0.0,1.0,4300,1.02,886,1597,1,15000,59,2
8,91475,investment,2012-05-25,1,1.0,0,1.0,0.0,3900,0.65,1837,3795,1,12000,24,1

# EDA

In [446]:
df[df['avg_percentage_credit_card_limit_used_last_year']==0]

,loan_id,loan_purpose,date,loan_granted,loan_repaid,is_first_loan,fully_repaid_previous_loans,currently_repaying_other_loans,total_credit_card_limit,avg_percentage_credit_card_limit_used_last_year,saving_amount,checking_amount,is_employed,yearly_salary,age,dependent_number
26806,432059,other,2012-06-19,1,1.0,0,1.0,0.0,7800,0.0,2834,6900,1,52500,31,2
47696,264583,business,2012-09-14,1,1.0,0,1.0,1.0,5600,0.0,480,3928,1,41500,28,4

In [447]:
df.drop([26806,47696],axis=0,inplace=True)

In [448]:
df[df['avg_percentage_credit_card_limit_used_last_year']==0]

Empty DataFrame
Columns: [loan_id, loan_purpose, date, loan_granted, loan_repaid, is_first_loan, fully_repaid_previous_loans, currently_repaying_other_loans, total_credit_card_limit, avg_percentage_credit_card_limit_used_last_year, saving_amount, checking_amount, is_employed, yearly_salary, age, dependent_number]
Index: []

In [449]:
for i in df.columns:
    if df[i].isnull().sum()!=0 and i!='avg_percentage_credit_card_limit_used_last_year':
        df[i].fillna(-1,inplace=True)
    else:
        df[i].fillna(0,inplace=True)

In [450]:
df.head()

,loan_id,loan_purpose,date,loan_granted,loan_repaid,is_first_loan,fully_repaid_previous_loans,currently_repaying_other_loans,total_credit_card_limit,avg_percentage_credit_card_limit_used_last_year,saving_amount,checking_amount,is_employed,yearly_salary,age,dependent_number
3,580653,other,2012-06-27,1,1.0,0,1.0,0.0,5400,0.52,3345,2764,1,15800,58,4
4,172419,business,2012-05-21,1,0.0,1,-1.0,-1.0,2900,0.76,1050,3695,1,34800,31,4
6,780070,business,2012-03-14,1,1.0,0,1.0,0.0,7800,0.30,4206,4368,1,51100,51,2
7,303138,emergency_funds,2012-08-31,1,0.0,0,0.0,1.0,4300,1.02,886,1597,1,15000,59,2
8,91475,investment,2012-05-25,1,1.0,0,1.0,0.0,3900,0.65,1837,3795,1,12000,24,1

In [453]:
categorical=[i for i in df.columns if df[i].dtype=='object']

In [454]:
categorical

['loan_purpose', 'date']

In [455]:
df.drop(['date'],axis=1,inplace=True)

In [456]:
df.loan_purpose.unique()

array(['other', 'business', 'emergency_funds', 'investment', 'home'],
      dtype=object)

In [457]:
y = pd.get_dummies(df.loan_purpose, prefix='Purpose',drop_first=True)

In [458]:
df=pd.concat([df,y],axis=1).drop(['loan_purpose'],axis=1)

In [459]:
df['total_amount']=df['saving_amount']+df['checking_amount']

In [460]:
df.drop(['saving_amount','checking_amount'],axis=1,inplace=True)

In [362]:
'''
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler
scaler2 = RobustScaler()
scaler1 = StandardScaler()
df2['age_scale']=pd.Series(scaler1.fit_transform(np.array(df2.age).reshape(-1,1)).reshape(len(df2.age),))
df2[['credit_limit_scale','total_amount_scale','salary_scale']]=pd.DataFrame(scaler2.fit_transform(df2[['total_credit_card_limit','total_amount','yearly_salary']]))
'''

C:\Users\yzhhu\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\yzhhu\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

In [363]:
df2.drop(['total_credit_card_limit','total_amount','yearly_salary','age'],axis=1,inplace=True)

In [434]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df.loan_purpose=le.fit_transform(df.loan_purpose)

In [461]:


loan_id=df['loan_id']

y=df['loan_repaid']
x=df.drop(['loan_id','loan_repaid','loan_granted'],axis=1)
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.20, random_state=42)

In [462]:
from sklearn.linear_model import LogisticRegression

lr=LogisticRegression(solver='lbfgs')
lr.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [473]:
pred=lr.predict(X_test)

In [474]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test,pred)
(1084+624)/np.sum(confusion_matrix(Y_test,pred))

0.17920470045115938

In [442]:
from sklearn.model_selection import train_test_split, cross_val_score, cross_val_predict
from sklearn.linear_model import LogisticRegression

# Initiating the model:
lr = LogisticRegression(solver='lbfgs')

scores = cross_val_score(lr, X_train, Y_train, scoring='accuracy' ,cv=10).mean()

print("The mean accuracy with 10 fold cross validation is %s" % round(scores*100,2))

C:\Users\yzhhu\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\yzhhu\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\yzhhu\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\yzhhu\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\yzhhu\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\yzhhu\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)

The mean accuracy with 10 fold cross validation is 83.13

In [328]:
list(pred)

[1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 ...]

In [288]:
Y_test

6541      1
46240     0
47827     0
70934     1
72479     0
33918     0
38537     1
60900     1
100005    0
23420     1
62977     1
67360     0
1570      1
64848     1
100292    0
89357     0
44643     1
79462     1
17233     1
59107     0
55665     1
84466     1
16420     0
70598     0
78003     0
53771     1
74867     1
67488     0
61102     1
17502     0
         ..
38512     0
68072     1
2556      0
6429      0
28304     0
34045     0
91899     0
90719     0
31244     1
49196     1
65880     0
24639     1
83230     1
29810     1
85637     0
86316     0
11451     0
83875     0
73455     0
55376     0
94316     0
43650     1
49552     1
13933     1
81854     1
46423     1
4065      1
46809     0
76247     1
50394     0
Name: loan_granted, Length: 20220, dtype: int64

In [245]:
x

,loan_repaid,is_first_loan,fully_repaid_previous_loans,currently_repaying_other_loans,avg_percentage_credit_card_limit_used_last_year,is_employed,dependent_number,Purpose_emergency_funds,Purpose_home,Purpose_investment,Purpose_other,loan_repaid2,age_scale,credit_limit_scale,total_amount_scale,salary_scale
0,-1.0,1,-1.0,-1.0,0.79,1,7,0,0,1,0,-1.0,0.039619,1.607143,0.947833,0.671388
1,-1.0,1,-1.0,-1.0,0.52,0,5,0,0,1,0,-1.0,0.039619,0.428571,0.469764,-0.609065
2,-1.0,1,-1.0,-1.0,0.00,1,4,0,0,0,1,-1.0,1.443071,-1.464286,-0.060213,0.141643
3,1.0,0,1.0,0.0,0.52,1,4,0,0,0,1,1.0,1.287131,0.464286,0.515183,-0.161473
4,0.0,1,-1.0,-1.0,0.76,1,4,0,0,0,0,0.0,-0.818046,-0.428571,0.161173,0.376771
5,-1.0,1,-1.0,-1.0,0.82,0,3,0,0,0,1,-1.0,0.273527,-0.392857,0.044900,-0.609065
6,1.0,0,1.0,0.0,0.30,1,2,0,0,0,0,1.0,0.741345,1.321429,1.154944,0.838527
7,0.0,0,0.0,1.0,1.02,1,2,1,0,0,0,0.0,1.365101,0.071429,-0.425902,-0.184136
8,1.0,0,1.0,0.0,0.65,1,1,0,0,1,0,1.0,-1.363833,-0.071429,0.391383,-0.269122
9,-1.0,0,1.0,1.0,1.09,0,2,0,0,0,0,-1.0,-0.428199,-1.107143,-0.670127,-0.609065
10,-1.0,0,1.0,1.0,1.07,1,5,0,1,0,0,-1.0,-0.896016,0.964286,-0.131586,0.209632
11,-1.0,1,-1.0,-1.0,0.89,0,2,0,0,0,0,-1.0,2.690583,0.214286,0.026732,-0.609065
12,-1.0,1,-1.0,-1.0,0.83,0,3,0,1,0,0,-1.0,2.846522,-0.464286,-0.013756,-0.609065
13,-1.0,1,-1.0,-1.0,0.73,1,2,0,0,1,0,-1.0,-0.662107,0.357143,2.560602,-0.223796
14,-1.0,1,-1.0,-1.0,0.00,0,3,0,1,0,0,-1.0,1.053223,-1.464286,-0.394757,-0.609065
15,0.0,0,1.0,1.0,0.42,1,1,1,0,0,0,0.0,-0.272259,0.714286,-0.233844,0.082153
16,-1.0,1,-1.0,-1.0,0.73,1,8,0,1,0,0,-1.0,-0.973985,-0.750000,2.416039,0.291785
17,-1.0,0,1.0,1.0,0.41,0,5,0,0,1,0,-1.0,-0.428199,-0.107143,-0.208928,-0.609065
18,0.0,1,-1.0,-1.0,0.98,1,8,0,1,0,0,0.0,1.599010,-0.321429,-0.453153,-0.110482
19,-1.0,1,-1.0,-1.0,0.87,0,2,0,0,1,0,-1.0,1.521040,0.392857,-0.154944,-0.609065
20,-1.0,1,-1.0,-1.0,0.38,1,2,0,1,0,0,-1.0,-1.441803,0.714286,1.528679,0.509915
21,-1.0,0,1.0,0.0,1.02,0,2,0,1,0,0,-1.0,0.117588,0.607143,-0.070854,-0.609065
22,1.0,0,1.0,0.0,0.85,1,3,0,1,0,0,1.0,1.287131,0.178571,1.635090,1.648725
23,1.0,0,1.0,0.0,0.59,1,1,0,0,0,0,1.0,-0.896016,2.142857,-0.037373,0.628895
24,-1.0,0,1.0,0.0,0.62,0,6,0,0,1,0,-1.0,-0.350229,1.214286,0.184272,-0.609065
25,1.0,1,-1.0,-1.0,0.59,1,8,0,0,0,0,1.0,-1.129924,0.000000,0.185051,0.849858
26,-1.0,1,-1.0,-1.0,0.96,0,8,1,0,0,0,-1.0,-1.519772,-1.000000,-0.678692,-0.609065
27,-1.0,1,-1.0,-1.0,0.68,1,4,1,0,0,0,-1.0,-0.896016,0.142857,1.094991,0.614731
28,1.0,1,-1.0,-1.0,0.71,1,7,0,1,0,0,1.0,-0.428199,0.000000,-0.152608,0.521246
29,-1.0,1,-1.0,-1.0,0.77,0,2,1,0,0,0,-1.0,0.273527,-0.285714,0.236180,-0.609065
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101070,-1.0,1,-1.0,-1.0,0.87,0,8,0,1,0,0,1.0,2.222766,-0.107143,0.869712,0.838527
101071,0.0,0,1.0,1.0,0.83,0,4,0,0,0,1,-1.0,0.429466,-0.107143,0.059434,-0.609065
101072,1.0,0,1.0,0.0,0.94,1,3,0,1,0,0,0.0,0.585406,-0.857143,-0.508175,0.053824
101073,-1.0,1,-1.0,-1.0,0.91,0,3,0,1,0,0,1.0,1.131192,1.142857,0.567610,0.419263
101074,0.0,1,-1.0,-1.0,0.44,1,0,0,0,0,0,1.0,1.053223,0.071429,0.272515,0.328612
101075,1.0,1,-1.0,-1.0,0.73,1,8,0,1,0,0,1.0,0.429466,-0.428571,0.512328,0.552408
101076,1.0,0,1.0,1.0,0.65,1,8,0,1,0,0,0.0,0.429466,0.392857,-0.465352,0.356941
101077,1.0,1,-1.0,-1.0,0.55,1,3,0,0,0,0,-1.0,1.209162,0.035714,-0.415780,-0.609065
101078,0.0,1,-1.0,-1.0,0.87,1,4,0,0,0,0,-1.0,-0.038351,1.178571,-0.704127,0.422096
101079,-1.0,1,-1.0,-1.0,0.81,0,5,0,1,0,0,-1.0,2.924492,-0.464286,-0.700753,-0.609065
101080,-1.0,1,-1.0,-1.0,1.05,1,3,0,1,0,0,-1.0,-0.818046,-1.250000,-0.682066,0.008499
101081,-1.0,1,-1.0,-1.0,0.95,0,8,0,0,1,0,0.0,0.195558,-0.535714,-0.331690,0.056657
101082,-1.0,0,1.0,1.0,0.67,1,7,1,0,0,0,0.0,-0.116320,0.500000,-0.469764,-0.019830
101083,0.0,1,-1.0,-1.0,0.64,1,1,0,0,1,0,1.0,-1.441803,1.321429,1.930703,-0.237960
101084,0.0,1,-1.0,-1.0,0.82,1,2,0,0,1,0,-1.0,-1.285864,-0.500000,-0.117571,-0.246459
101085,1.0,0,1.0,0.0,0.87,1,1,0,0,1,0,1.0,-1.129924,0.250000,0.332209,0.184136
101086,-1.0,0,1.0,0.0,0.79,1,2,0,1,0,0,-1.0,1.053223,-0.821429,0.193615,-0.609065
101087,1.0,1,-1.0,-1.0,0.76,1,3,0,1,0,0,0.0,-1.675711,-0.785714,-0.034519,0.178470
101088,-1.0,1,-1.0,-1.0,0.89,0,1,0,0,0,0,-1.0,-0.428199,1.250000,2.529198,-0.090652
101089,0.0,0,1.0,1.0,0.78,1,3,1,0,0,0,-1.0,-0.194290,1.035714,0.772126,1.019830
101090,-1.0,0,1.0,0.0,0.39,1,3,0,1,0,0,-1.0,-0.662107,-0.714286,-0.650662,-0.609065
101091,-1.0,0,1.0,0.0,0.51,1,4,0,1,0,0,-1.0,-1.519772,-1.464286,-0.776019,-0.609065
101092,-1.0,1,-1.0,-1.0,0.79,0,8,1,0,0,0,0.0,-0.350229,-0.535714,-0.666494,0.441926
101093,-1.0,1,-1.0,-1.0,0.00,0,1,1,0,0,0,0.0,1.131192,-0.607143,-0.311186,0.439093
101094,0.0,0,1.0,1.0,0.83,1,4,0,0,0,0,0.0,1.365101,-0.357143,-0.467168,0.033994
101095,0.0,0,1.0,0.0,0.40,1,3,1,0,0,0,1.0,0.585406,0.178571,-0.355308,0.388102
101096,0.0,1,-1.0,-1.0,0.68,1,5,0,0,0,0,1.0,0.741345,0.857143,0.225798,-0.053824
101097,1.0,1,-1.0,-1.0,0.50,1,1,0,0,0,1,-1.0,1.599010,-0.357143,-0.070335,-0.609065
101098,1.0,0,1.0,0.0,0.70,1,4,0,0,0,0,NaN,NaN,NaN,NaN,NaN
101099,-1.0,1,-1.0,-1.0,0.58,0,1,0,0,0,1,NaN,NaN,NaN,NaN,NaN